In [1]:
import numpy as np

### Ejercicio 1: Crear un array de 10 elementos con ceros

In [2]:
arr_ceros = np.zeros(10)
print("Array de 10 ceros:", arr_ceros)

Array de 10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Ejercicio 2: Genera un array con los números del 1 al 20

In [3]:
array_1_20 = np.arange(1, 21)
print(array_1_20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Ejercicio 3: Números pares del 2 al 50.

In [4]:
array_pares = np.arange(2, 51, 2)
print("Ejercicio 3:", array_pares)

Ejercicio 3: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


### Ejercicio 5: Matriz 4x4 con valores aleatorios entre 0 y 1.

In [5]:
matriz_aleatoria = np.random.rand(4, 4)
print("Ejercicio 5:\n", matriz_aleatoria)

Ejercicio 5:
 [[0.56566663 0.1522419  0.5625318  0.1536479 ]
 [0.41712014 0.85306017 0.07635558 0.40801235]
 [0.99853469 0.35640811 0.1883848  0.08698316]
 [0.15839256 0.81275591 0.21363877 0.68223425]]


### Ejercicio 6: suma de arrays a=[1,2,3], b=[4,5,6].

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
suma = a + b
print("Ejercicio 6:", suma)

Ejercicio 6: [5 7 9]


### Ejercicio 7: multiplicación de matrices 3x3.

In [7]:
matriz1 = np.random.randint(1, 11, (3, 3))
matriz2 = np.random.randint(1, 11, (3, 3))

producto = np.dot(matriz1, matriz2)
print("Matriz 1:\n", matriz1)
print("Matriz 2:\n", matriz2)
print("Ejercicio 7 - Producto:\n", producto)

Matriz 1:
 [[6 7 8]
 [1 5 9]
 [2 5 1]]
Matriz 2:
 [[ 7 10  8]
 [ 5  3 10]
 [ 1  4  9]]
Ejercicio 7 - Producto:
 [[ 85 113 190]
 [ 41  61 139]
 [ 40  39  75]]


### Ejercicio 8: array de 15 valores aleatorios entre 1 y 100.

In [8]:
array_aleatorio = np.random.randint(1, 101, 15)
maximo = np.max(array_aleatorio)
minimo = np.min(array_aleatorio)
promedio = np.mean(array_aleatorio)

print("Ejercicio:", array_aleatorio)
print("Máximo:", maximo)
print("Mínimo:", minimo)
print("Promedio:", promedio)

Ejercicio: [90 75 28 69 48 86 61 88 84 90 38 89 15  7 30]
Máximo: 90
Mínimo: 7
Promedio: 59.86666666666667


### Ejercicio 9: matriz 5x5 con valores del 1 al 25.

In [9]:
matriz_5x5 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_5x5)

print("Ejercicio 9:\n", matriz_5x5)
print("Diagonal:", diagonal)

Ejercicio 9:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


### Ejercicio 10: matriz 5x5 de enteros aleatorios entre 1 y 20.

In [10]:
matriz_aleatoria = np.random.randint(1, 21, (5, 5))
suma_filas = matriz_aleatoria.sum(axis=1)
suma_columnas = matriz_aleatoria.sum(axis=0)

print("Ejercicio 10:\n", matriz_aleatoria)
print("Suma de filas:", suma_filas)
print("Suma de columnas:", suma_columnas)

Ejercicio 10:
 [[17 10 14 19 12]
 [ 9  3  7 10  2]
 [ 7 13 13 17 18]
 [ 2  5  2  9  1]
 [ 2 10  4  1  6]]
Suma de filas: [72 31 68 19 23]
Suma de columnas: [37 41 40 56 39]
